version: '2'

services:
  glb:
    image: alena1108/lb-service-haproxy:glb-v1
    tty: true
    ports:
      - "${GLB_PORT}:${GLB_PORT}"
    lb_config:
      port_rules:
        - source_port: ${GLB_PORT}
          protocol: http
          selector: io.rancher.glb.http=true
    labels:
      io.rancher.service.selector.link: io.rancher.glb=true
      io.rancher.container.create_agent: true
      io.rancher.container.agent.role: system
    command: ["lb-controller", "--controller", "rancherglb", "--provider",  "haproxy"]
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
