---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: lint-charts
  pull: default
  image: guangbo/chart-testing:v2.0.2-rancher1
  commands:
  - git remote add rancher-catalog https://github.com/1319104744/rancher-catalog
  - git fetch rancher-charts master
  - ct lint --config test/ct.yaml
