.catalog:
  name: "HNA Monnitoring and Logging Agent"
  version: "v0.3"
  description: "Monnitoring and Logging agent for HNA"
  minimum_rancher_version: v1.2.0
  questions:
    - variable: "INFLUXDB_RELAY_HOST"
      label: "Influxdb relay host"
      description: "Influxdb relay host"
      type: "string"
      default: "192.168.100.100:8086"
      required: true
