name: CMBC-User
description: CMBC user template
stacks:
  - name: network-services
    templateId: 'library:infra*network-services'
  - name: vxlan-user
    templateId: 'library:infra*vxlan-user'
  - name: scheduler
    templateId: 'library:infra*scheduler'
  - name: healthcheck
    templateId: 'library:infra*healthcheck'
