name: HNA-Admin
description: HNA admin template
stacks:
  - name: network-services
    templateId: 'library:infra*network-services'
  - name: vxlan-admin
    templateId: 'library:infra*vxlan-admin'
  - name: scheduler
    templateId: 'library:infra*scheduler'
  - name: healthcheck
    templateId: 'library:infra*healthcheck'
