name: HNA-User
description: HNA user template
stacks:
  - name: network-services
    templateId: 'library:infra*network-services'
  - name: ipsec
    templateId: 'library:infra*vxlan-user'
  - name: scheduler
    templateId: 'library:infra*scheduler'
  - name: healthcheck
    templateId: 'library:infra*healthcheck'
  - name: beancounter-agent
    templateId: 'library:infra*beancounter-agent'
