version: '2'

services:
  glb:
    image: rancher/lb-service-haproxy:v0.5.9
    tty: true
    ports:
      - ${GLB_SOURCE_PORT}:${GLB_LINK_PORT}
    labels:
      io.rancher.service.selector.link: io.rancher.glb=true
      io.rancher.container.create_agent: true
      io.rancher.container.agent.role: system
    command: ["lb-controller", "--controller", "rancherglb", "--provider",  "haproxy"]
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
